import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

async function technicalPoint(page: Page, coordinates: [number, number]) {
  await page.getByText('Szczegóły punktu: współrzędne', { exact: true }).click();
  await page.getByLabel('Szerokość geograficzna', { exact: true }).fill(String(coordinates[1]));
  await page.getByLabel('Długość geograficzna', { exact: true }).fill(String(coordinates[0]));
  await page.getByRole('button', { name: 'Ustaw punkt ze współrzędnych', exact: true }).click();
  await page.getByRole('button', { name: 'To miejsce obserwacji', exact: true }).click();
}

test('training grows the garden, buys decorations once and never writes observations', async ({ page }) => {
  const writes: string[] = [];
  const errors: string[] = [];
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/')) writes.push(request.url()); });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/gra?tryb=ogrod');
  await expect(page).toHaveTitle('Iskry Miasta · Twój mały ogród');
  await expect(page.locator('link[rel="manifest"]')).toHaveAttribute('href', '/iskry.webmanifest');
  const manifest = await (await page.request.get('/iskry.webmanifest')).json();
  expect(manifest.start_url).toBe('/gra'); expect(manifest.id).toBe('/gra');
  await page.getByRole('button', { name: 'Zatrzymaj animacje ogrodu' }).click();
  await expect(page.locator('.ig-bird > svg')).toHaveCSS('animation-play-state', 'paused');
  await page.getByRole('button', { name: 'Zacznij małe odkrycie' }).click();
  await expect(page.getByRole('heading', { name: 'Brama z niespodzianką' })).toBeFocused();
  await page.getByRole('button', { name: /Szerokie drzwi wystarczą/ }).click();
  await expect(page.getByRole('status')).toContainText('Spójrz na dolną krawędź drzwi');
  await expect(page.locator('.ig-garden-stats')).toContainText('0 iskier');
  await page.getByRole('button', { name: /Przed wejściem jest stopień/ }).click();
  await expect(page.getByRole('heading', { name: 'Pierwsze pędy' })).toBeVisible();
  await expect(page.locator('.ig-garden-gift')).toContainText('+20 iskier');
  await expect(page.locator('.ig-garden-gift')).toHaveCSS('opacity', '1');
  await expect(page.locator('.ig-world .ig-sprout-in').first()).toHaveCSS('animation-name', 'none');
  await page.getByRole('button', { name: 'Łąka iskier, 15 iskier, grządka 1', exact: true }).click();
  await expect(page.locator('.ig-garden-stats')).toContainText('5 iskier');
  await expect(page.getByRole('button', { name: 'Grządka 1, z ozdobą' })).toBeVisible();
  await page.getByRole('button', { name: 'Grządka 3, pusta' }).click();
  await page.getByRole('button', { name: 'Łąka iskier, odblokowana, ustaw bez kosztu, grządka 3' }).click();
  await expect(page.getByRole('button', { name: 'Grządka 3, z ozdobą' })).toBeVisible();
  await expect(page.locator('.ig-garden-stats')).toContainText('5 iskier');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await page.reload();
  await expect(page.getByRole('button', { name: /01 Brama z niespodzianką|Brama z niespodzianką.*Gotowe/ })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Grządka 3, z ozdobą' })).toBeVisible();
  await page.getByRole('button', { name: /02 Miara ma znaczenie/ }).click();
  await page.getByRole('button', { name: /86 cm wolnego przejścia/ }).click();
  await expect(page.getByRole('heading', { name: 'Zielona przystań' })).toBeVisible();
  expect(writes).toEqual([]); expect(errors).toEqual([]);
});

test('mobile training has keyboard access, reduced motion and a separate guest city gate', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/gra?tryb=ogrod');
  await expect(page.getByRole('button', { name: 'Zatrzymaj animacje ogrodu' })).toBeHidden();
  const first = page.getByRole('button', { name: 'Zacznij małe odkrycie' });
  await first.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name: 'Brama z niespodzianką' })).toBeFocused();
  await expect(page.getByRole('heading', { name: 'Brama z niespodzianką' })).toBeInViewport();
  await page.getByRole('button', { name: /Przed wejściem jest stopień/ }).click();
  await expect(page.locator('.ig-garden-gift')).toBeInViewport();
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await page.getByRole('button', { name: 'Moje miasto', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Zabierz Iskrę do miasta.' })).toBeVisible();
  await expect(page.locator('.ig-garden-stats')).toContainText('0 iskier');
  await expect(page.getByRole('link', { name: /Przejdź do konta/ })).toHaveAttribute('href', '/app?konto=1');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Trening', exact: true }).click();
  await expect(page.locator('.ig-garden-stats')).toContainText('20 iskier');
});

test('city observation uses the signed in account and server reward, then persists its decoration', async ({ page }) => {
  const registration = await page.request.post('/api/auth/register', { data: { email: `game-${Date.now()}@example.invalid`, password: 'Synthetic-local-test-2026!', displayName: 'Tester ogrodu' } });
  expect(registration.status()).toBe(201);
  const account = await (await page.request.get('/api/auth/me')).json();
  await page.goto('/gra?tryb=ogrod');
  await page.getByRole('button', { name: 'Moje miasto', exact: true }).click();
  await page.getByRole('button', { name: /Wypatrz przewężenie/ }).first().click();
  const list = await (await page.request.get('/api/game/missions')).json();
  const mission = list.missions.find((item: { kind: string }) => item.kind === 'width');
  await technicalPoint(page, mission.target.coordinates);
  await page.getByLabel('Zmierzona wolna szerokość w cm').fill('85');
  await page.getByLabel('Co dokładnie zauważono?').fill('Syntetyczna obserwacja wyłącznie w izolowanej bazie testowej między słupkiem a ścianą budynku.');
  await page.getByRole('checkbox').check();
  const reportResponse = page.waitForResponse(response => response.url().endsWith('/api/reports') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Zapisz obserwację i odbierz iskry' }).click();
  const report = await (await reportResponse).json();
  await expect(page.locator('.ig-garden-gift')).toContainText('+20 iskier');
  expect(report.isMine).toBe(true); expect(report.userId).toBeUndefined();
  const decorationResponse = page.waitForResponse(response => response.url().endsWith('/api/game/decorate') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Łąka iskier, 15 iskier, grządka 1', exact: true }).click();
  expect((await decorationResponse).status()).toBe(200);
  await expect(page.locator('.ig-garden-stats')).toContainText('5 iskier');
  const state = await (await page.request.get('/api/game/state')).json();
  expect(state.earned).toBe(20); expect(state.spent).toBe(15); expect(state.observations).toBe(1);
  expect(state.decorations).toEqual([{ slot: 0, itemId: 'flowers' }]);
  const replay = await page.request.post('/api/game/claim', { data: { reportId: report.id, missionId: mission.id, expectedUserId: account.user.id } });
  expect((await replay.json()).awarded).toBe(0);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
});

test('positive training discoveries add a rest corner and open doors without API writes', async ({ page }) => {
  const writes: string[] = [];
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/')) writes.push(request.url()); });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/gra?tryb=ogrod');
  await page.getByRole('button', { name: /05 Miejsce na oddech/ }).click();
  await page.getByRole('button', { name: /Dodam ją jako przeszkodę/ }).click();
  await expect(page.getByRole('status')).toContainText('Dobre miejsce to osobne odkrycie');
  await page.getByRole('button', { name: /Opiszę ławkę, jej położenie i dojście/ }).click();
  await expect(page.getByText('Zakątek odpoczynku', { exact: true })).toBeVisible();
  await expect(page.locator('.ig-garden-stats')).toContainText('20 iskier');
  await page.getByRole('button', { name: 'Kolejne odkrycie', exact: true }).click();
  await page.getByRole('button', { name: /06 Drzwi do odkrycia/ }).click();
  await page.getByRole('button', { name: /To wejście nie ma schodów; szerokość/ }).click();
  await expect(page.getByText('Otwarte drzwi', { exact: true })).toBeVisible();
  await expect(page.locator('.ig-garden-stats')).toContainText('40 iskier');
  await expect(page.locator('.ig-petal-burst')).toBeHidden();
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  expect(writes).toEqual([]);
});

test('positive city discovery is public separately, earns once and can be withdrawn without a barrier', async ({ page }) => {
  const registration = await page.request.post('/api/auth/register', { data: { email: `good-discovery-${Date.now()}@example.invalid`, password: 'Synthetic-local-test-2026!', displayName: 'Tester dobrych miejsc' } });
  expect(registration.status()).toBe(201);
  const before = await (await page.request.get('/api/reports')).json();
  const writes: string[] = [];
  page.on('request', request => { if (request.method() === 'POST') writes.push(new URL(request.url()).pathname); });
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: (callback: PositionCallback) => { (window as unknown as { delayedGameGPS: PositionCallback }).delayedGameGPS = callback; } } });
  });
  await page.goto('/gra?tryb=ogrod');
  await page.getByRole('button', { name: 'Moje miasto', exact: true }).click();
  await page.getByRole('button', { name: 'Dobre odkrycia', exact: true }).click();
  await expect(page.getByRole('button', { name: /Wypatrz przewężenie/ })).toHaveCount(0);
  await page.getByRole('button', { name: /Odkryj przystanek odpoczynku/ }).first().click();
  await expect(page.getByText('Osobne dobre odkrycie.', { exact: true })).toBeVisible();
  const list = await (await page.request.get('/api/game/missions')).json();
  const mission = list.missions.find((item: { kind: string }) => item.kind === 'rest_place');
  await expect(page.getByRole('button', { name: 'To miejsce obserwacji', exact: true })).toBeDisabled();
  await page.getByRole('combobox', { name: 'Adres w okolicy obserwacji' }).fill('Rynek Główny 1');
  await page.getByRole('listbox', { name: 'Podpowiedzi: Adres w okolicy obserwacji' }).getByRole('option', { name: /Rynek Główny 1, Kraków/ }).first().click();
  await expect(page.getByRole('button', { name: 'To miejsce obserwacji', exact: true })).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Zapisz obserwację i odbierz iskry' })).toBeDisabled();
  await page.getByRole('button', { name: 'Użyj mojego GPS', exact: true }).click();
  await page.getByRole('button', { name: 'Wróć do misji', exact: true }).click();
  await page.getByRole('button', { name: /Odkryj przystanek odpoczynku/ }).first().click();
  await page.evaluate(() => (window as unknown as { delayedGameGPS: PositionCallback }).delayedGameGPS({ coords: { longitude: 20.11, latitude: 50.12, accuracy: 5 } } as GeolocationPosition));
  await expect(page.getByRole('button', { name: 'To miejsce obserwacji', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Ustaw pinezkę w środku mapy', exact: true })).toBeEnabled();
  const mapCanvas = page.getByRole('region', { name: 'Mapa punktu obserwacji', exact: true }).locator('canvas');
  const mapBox = await mapCanvas.boundingBox(); expect(mapBox).not.toBeNull();
  await mapCanvas.click({ position: { x: mapBox!.width * .65, y: mapBox!.height * .45 } });
  const selectedPoint = [Number(await page.getByLabel('Długość geograficzna', { exact: true }).inputValue()), Number(await page.getByLabel('Szerokość geograficzna', { exact: true }).inputValue())];
  expect(Math.abs(selectedPoint[0] - mission.target.coordinates[0]) + Math.abs(selectedPoint[1] - mission.target.coordinates[1])).toBeGreaterThan(.000001);
  await expect(page.getByRole('button', { name: 'Zapisz obserwację i odbierz iskry' })).toBeDisabled();
  await page.getByRole('button', { name: 'To miejsce obserwacji', exact: true }).click();
  await page.getByLabel('Co dokładnie zauważono?').fill('Syntetyczna ławka z oparciem przy północnej alejce, wyłącznie w izolowanej bazie testowej.');
  await page.getByRole('checkbox').check();
  const response = page.waitForResponse(value => value.url().endsWith('/api/observations') && value.request().method() === 'POST');
  await page.getByRole('button', { name: 'Zapisz obserwację i odbierz iskry' }).click();
  const observation = await (await response).json();
  expect(observation.coordinates).toEqual(selectedPoint);
  await expect(page.locator('.ig-garden-gift')).toContainText('+15 iskier');
  expect(observation.verification).toBe('unverified'); expect(observation.affectsRouting).toBe(false);
  expect((await (await page.request.get('/api/reports')).json()).reports.length).toBe(before.reports.length);
  const publicItems = await (await page.request.get('/api/observations')).json();
  expect(publicItems.observations.some((item: { id: string }) => item.id === observation.id)).toBe(true);
  await page.getByRole('button', { name: 'Moje odkrycia', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Moje dobre odkrycia' })).toBeVisible();
  await expect(page.getByText('Publiczna obserwacja', { exact: true })).toBeVisible();
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([]);
  await page.getByRole('button', { name: 'Wycofaj odkrycie', exact: true }).click();
  await expect(page.getByText('Wycofane', { exact: true })).toBeVisible();
  const after = await (await page.request.get('/api/observations')).json();
  expect(after.observations.some((item: { id: string }) => item.id === observation.id)).toBe(false);
  expect((await (await page.request.get('/api/game/state')).json()).earned).toBe(15);
  expect(writes).not.toContain('/api/reports');
});
